import type { NextPage } from 'next';
import Head from 'next/head';
import AddItems from '../components/AddItems';

import Items from '../components/Items';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<AddItems />
			<Items />
		</>
	);
};

export default Home;
