import type { NextPage } from 'next';
import Head from 'next/head';

import AddItems from '../components/AddItems';
import Items from '../components/Items';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar /> */}

      <div className="flex flex-col justify-center items-center mt-20">
        <AddItems />
        <Items />
      </div>
    </>
  );
};

export default Home;
